### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by shuzootani** [shuzootani/react-basic-sample-app#1]
## test with jest
- [ ] available restaurants and dishes filtered by meal and restaurant.
- [ ] validate invalid input value
...

## validation
- [ ] number of dishes matches number of ppl
- [ ] duplicated dish order is not allowed
- [ ] unable to move next unless go through valid input processes

## features
- [ ] editable order
- [ ] deletable order
- [ ] error handle
- [ ] move to order complete component after submit
